# Generated by Django 3.0.5 on 2020-04-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200407_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuniquedata',
            name='message',
            field=models.TextField(),
        ),
    ]
