# Generated by Django 3.0.5 on 2020-04-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200407_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuniquedata',
            name='cube',
            field=models.CharField(blank=True, choices=[('spam', 'spam'), ('not-spam', 'not-spam')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cuniquedata',
            name='google',
            field=models.CharField(blank=True, choices=[('spam', 'spam'), ('not-spam', 'not-spam')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cuniquedata',
            name='ibm',
            field=models.CharField(blank=True, choices=[('spam', 'spam'), ('not-spam', 'not-spam')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cuniquedata',
            name='truth',
            field=models.CharField(blank=True, choices=[('spam', 'spam'), ('not-spam', 'not-spam')], max_length=10, null=True),
        ),
    ]
