# Generated by Django 3.0.5 on 2020-04-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuniqueData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('truth', models.CharField(blank=True, choices=[('spam', 'spam'), ('not-spam', 'not-spam')], max_length=10, null=True)),
                ('cube', models.CharField(blank=True, choices=[('spam', 'spam'), ('not-spam', 'not-spam')], max_length=10, null=True)),
                ('google', models.CharField(blank=True, choices=[('spam', 'spam'), ('not-spam', 'not-spam')], max_length=10, null=True)),
                ('ibm', models.CharField(blank=True, choices=[('spam', 'spam'), ('not-spam', 'not-spam')], max_length=10, null=True)),
                ('google_spam', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True)),
                ('google_not_spam', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True)),
                ('ibm_spam', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True)),
                ('ibm_not_spam', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True)),
            ],
        ),
    ]
